import "./globals.css";

export const metadata = {
    title: "Web Tutoials",
    description: "Generated by JuYEON",
};

export default function RootLayout({ children }) {
    return (
        <html>
            <body>
                <a href="/">
                    <h1>WEB</h1>
                </a>
                <ol>
                    <li>
                        <a href="/read/1">html</a>
                    </li>
                    <li>
                        <a href="/read/2">css</a>
                    </li>
                </ol>
                {children}
                <ul>
                    <li>
                        <a href="/create">CREATE</a>
                    </li>
                    <li>
                        <a href="/update/1">Update</a>
                    </li>
                    <li>
                        <input type="button" value="Delete"></input>
                    </li>
                </ul>
            </body>
        </html>
    );
}
