"use client";
import Link from "next/link";
import "./globals.css";
import { useState, useEffect } from "react";

//// metadata- ServerComp에서만 사용
// export const metadata = {
//     title: "Web Tutoials",
//     description: "Generated by JuYEON",
// };

export default function RootLayout({ children }) {
    const [topics, setTopics] = useState([]);

    // 서버에서 클라이언트로 데이터 가져오기 - useEffect사용
    // 한 번만 실행예정 == 빈 배열 넣기
    useEffect(() => {
        fetch("http://localhost:9999/topics")
            .then((resp) => resp.json())
            .then((result) => {
                setTopics(result);
            });
    }, []);

    return (
        <html>
            <body>
                <Link href="/">
                    <h1>WEB</h1>
                </Link>
                <ol>
                    {topics.map((topic) => {
                        return (
                            <li key={topic.id}>
                                <Link href={`/read/${topic.id}`}>
                                    {topic.title}
                                </Link>
                            </li>
                        );
                    })}
                </ol>
                {children}
                <ul>
                    <li>
                        <Link href="/create">CREATE</Link>
                    </li>
                    <li>
                        <Link href="/update/1">Update</Link>
                    </li>
                    <li>
                        <input type="button" value="Delete"></input>
                    </li>
                </ul>
            </body>
        </html>
    );
}
